# Generated by Django 3.0.3 on 2020-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('query', models.TextField(null=True)),
                ('institute', models.CharField(choices=[('kalyani', 'IIIT Kalyani'), ('guwhati', 'IIIT Guwhati')], default='kalyani', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
    ]
