# Generated by Django 3.0.3 on 2020-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20200907_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='secret_code_value',
            field=models.CharField(default='0e9e2e3303', max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='secret_code',
            field=models.CharField(max_length=10),
        ),
    ]
