# Generated by Django 3.0.3 on 2020-09-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200907_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='secret_code_value',
            field=models.CharField(default='85f868ece9', max_length=10),
        ),
    ]
