# Generated by Django 3.0.3 on 2020-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200907_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='secret_code_value',
            field=models.CharField(default='dYKoiaerKd', max_length=10),
        ),
    ]
