# Generated by Django 3.0.3 on 2020-09-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20200907_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='institute',
            field=models.CharField(choices=[('general', 'General'), ('kalyani', 'IIIT Kalyani'), ('guwhati', 'IIIT Guwhati'), ('bhagalpur', 'IIIT Bhagalpur'), ('bhopal', 'IIIT Bhopal'), ('dharwad', 'IIIT Dharwad'), ('gwalior', 'IIIT Gwalior'), ('jabalpur', 'IIIT Jabalpur'), ('kancheepuram', 'IIIT Kancheepuram'), ('kota', 'IIIT Kota'), ('kurnool', 'IIIT Kurnool'), ('lucknow', 'IIIT Lucknow'), ('nagpur', 'IIIT Nagpur'), ('pune', 'IIIT Pune'), ('raichur', 'IIIT Raichur'), ('ranchi', 'IIIT Ramchi'), ('sonepat', 'IIIT Sonepat'), ('sricity', 'IIIT Sricity'), ('surat', 'IIIT Surat'), ('tiruchirapalli', 'IIIT Tiruchirapalli'), ('una', 'IIIT Una'), ('vadodara', 'IIIT Vadodara'), ('kottayam', 'IIIT Kottayam'), ('manipur', 'IIIT Manipur'), ('agartala', 'IIIT Agartala'), ('allahabad', 'IIIT Allahabad')], default='kalyani', max_length=20),
        ),
    ]
